### ISSUE TITLE
Login Response: Not found

### ISSUE THREAD

**Issue by sirjowee** [samie820/hooks-state-management-backend#1]
I was try login into the app using the follwoing credentials but is telling me Not found.

email|username: admin
password: password
<img width="788" alt="Screenshot 2019-09-11 at 9 25 55 PM" src="https://user-images.githubusercontent.com/28712864/64732380-cc79bc80-d4da-11e9-8b56-a8a8df86532a.png">

**Comment by samie820** [comment]
Sorry for slowest response time in history, but this has been fixed
